sudo: required
dist: trusty
language: C
services:
  - docker
env:
  - PG_SUPPORTED_VERSIONS=9.3 DIST=trusty
  - PG_SUPPORTED_VERSIONS=9.4 DIST=trusty
  - PG_SUPPORTED_VERSIONS=9.5 DIST=trusty
  - PG_SUPPORTED_VERSIONS=9.6 DIST=trusty
  - PG_SUPPORTED_VERSIONS=10  DIST=trusty
  - PG_SUPPORTED_VERSIONS=11  DIST=trusty
  - PG_SUPPORTED_VERSIONS=12  DIST=trusty
  - PG_SUPPORTED_VERSIONS=9.3 DIST=xenial
  - PG_SUPPORTED_VERSIONS=9.4 DIST=xenial
  - PG_SUPPORTED_VERSIONS=9.5 DIST=xenial
  - PG_SUPPORTED_VERSIONS=9.6 DIST=xenial
  - PG_SUPPORTED_VERSIONS=10  DIST=xenial
  - PG_SUPPORTED_VERSIONS=11  DIST=xenial
  - PG_SUPPORTED_VERSIONS=12  DIST=xenial
before_install:
  - docker pull heroku/dod-package-dev:$DIST
  - mkdir -p ../deb-build ../packages/$DIST
  - |
    cat <<'EOF' > ../deb-build/build.sh
    #!/bin/sh -x

    export DEBIAN_FRONTEND=noninteractive

    wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
    case $PG_SUPPORTED_VERSIONS in
      11|12)
      # update pgdg-source.list
      sed -i -e "s/pgdg.*/pgdg-testing main $PG_SUPPORTED_VERSIONS/" /etc/apt/sources.list.d/pgdg*.list
      export DIST=$DIST-pgdg-testing
      ;;
      *)
      export DIST=$DIST-pgdg
      ;;
    esac

    apt-get update -y
    apt-get install -y -t $DIST debhelper fakeroot postgresql-common postgresql-server-dev-all postgresql-server-dev-$PG_SUPPORTED_VERSIONS

    if [ ! -x /usr/lib/postgresql/$PG_SUPPORTED_VERSIONS/bin/postgres ]; then
      sudo /etc/init.d/postgresql stop # stop postgresql again before installing the server
      apt-get install -y postgresql-$PG_SUPPORTED_VERSIONS
    fi

    /etc/init.d/postgresql stop
    pg_lsclusters
    dpkg -l postgresql\* | cat

    cd /root/build/pgextwlist

    pg_buildext updatecontrol
    dpkg-buildpackage -us -uc -rfakeroot
    for deb in ../*.deb; do echo "$deb:"; dpkg-deb --info $deb; dpkg-deb --contents $deb; done
    sudo dpkg -i ../*.deb
    pg_buildext -i '--locale=C.UTF-8' -o local_preload_libraries=pgextwlist -o extwlist.extensions=citext,earthdistance,pg_trgm installcheck

  - chmod 755 ../deb-build/build.sh
script:
  - |
    docker run -v $(readlink -f ../deb-build):/root/deb-build \
               -v $(readlink -f ../packages/$DIST):/root/build \
               -v $(readlink -f .):/root/build/pgextwlist \
               -e DIST=$DIST -e PG_SUPPORTED_VERSIONS=$PG_SUPPORTED_VERSIONS \
               --privileged=true -it heroku/dod-package-dev:$DIST \
               bash -x /root/deb-build/build.sh
  - du -a ../packages/$DIST
deploy:
  - provider: packagecloud
    dist: ubuntu/$DIST
    package_glob: ../packages/$DIST/*.deb
    username: heroku
    repository: dod
    token:
      secure: Rw79hHuth3NMchjddRfZrbfDwRgJDUC88ITs7Y1pmLQtIyCV43PVwk3vBZ3OC/gJaBcLpDrH+mhkA4wxUSktRu6U8jwWpFGAFdtG7KR/7otaQyK+4e+E2dGr684UlvVTG688sh5Kc/q38pjvc3gI6irTITHImY8t/jNyAJf2ES58QZUopF/nEMbr7z/oudyNfB3ZBcLTnyqr7SB74jbZy4W0FdUDtdsja9KRf2Cc3/13gDIVCgZ4OJSUkfGdlWbvx6WXqDc/BiY1RDU6YP1IUGdNnfA2K9iIfBSkBKWvANrf15UR7YtXbWp1rkXzXlirkhY9iBC8wBKdl/M05xSFkOT0JcYI6vndB/qAXUOL8dt5G+GXO4pXkls7GnZN8N96mG5+xKmgcWPas/vwkzcygslwJC60Kez4A5CspLtead4drHcuaLTJtLox8fMLxHtmMWJAtwDfhW40kCrR9RCE97FEJBW6Pa8qiVt9sjsPhvQfWtp9r1gWqOyUUoR3VmrGNEwJZQXN8suIkenmHPerqMVnrx7KNYFQUtdWsG8d6WDEq6R64LJgmGGJ3ixi8afW3LUAuDg6qw1lz0peCOn+X4XA7WhWRcTbkvNgbswvjZmtJiq2wGym74YD4H477bNT/mps3dUlwm8AddUOcae26bBfUA9+p5cB1j55STq+eZ0=
    skip_cleanup: true
notifications:
  email: false
