# run the testsuite on travis-ci.com
---
# versions to run on
env:
  - PG_SUPPORTED_VERSIONS=9.3
  - PG_SUPPORTED_VERSIONS=9.4
  - PG_SUPPORTED_VERSIONS=9.5
  - PG_SUPPORTED_VERSIONS=9.6
  - PG_SUPPORTED_VERSIONS=10
  - PG_SUPPORTED_VERSIONS=11
  - PG_SUPPORTED_VERSIONS=12
  - PG_SUPPORTED_VERSIONS=13

arch:
 - amd64
 - ppc64le
language: c
os: linux
dist: focal

before_install:
  # travis' postgresql-common is missing apt.postgresql.org.sh (2020-05-21)
  - sudo apt-get -qq update
  - sudo apt-get -y install postgresql-common

install:
  - sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -p -v $PG_SUPPORTED_VERSIONS -i
  # apt.pg.o.sh doesn't install contrib yet
  - sudo apt-get -y install postgresql-contrib-$PG_SUPPORTED_VERSIONS

script:
  - make PROFILE="-Werror"
  - sudo make install
  - sudo mkdir $(pg_config --pkglibdir)/plugins
  - sudo ln -s ../pgextwlist.so $(pg_config --pkglibdir)/plugins
  - pg_virtualenv -i '--locale=C.UTF-8' -o local_preload_libraries=pgextwlist -o extwlist.extensions=citext,earthdistance,pg_trgm,pg_stat_statements -o extwlist.custom_path=$PWD/test-scripts make installcheck
  - if test -s regression.diffs; then cat regression.diffs; fi
