#!/bin/sh

set -e

pg_buildext \
	-o local_preload_libraries=pgextwlist \
	-o extwlist.extensions=citext,earthdistance,pg_trgm,pg_stat_statements \
	-o extwlist.custom_path=$PWD/test-scripts \
	installcheck
